---
swagger: "2.0"
info:
  description: "tinkoff.ru/invest OpenAPI."
  version: "1.0.0"
  title: "OpenAPI"
  termsOfService: "#"
  contact:
    email: "n.v.melnikov@tinkoff.ru"
tags:
- name: "sandbox"
  description: "Операция в sandbox"
- name: "orders"
  description: "Операции заявок"
- name: "portfolio"
  description: "Операции с портфелем пользователя"
- name: "market"
  description: "Получении информации по бумагам"
- name: "operations"
  description: "Получении информации по операциям"
- name: "user"
  description: "Получении информации по брокерским счетам"
paths:
  /sandbox/register:
    post:
      tags:
      - "sandbox"
      summary: "Регистрация клиента в sandbox"
      description: "Создание счета и валютных позиций для клиента"
      parameters: []
      responses:
        "200":
          description: "Успешный ответ"
        "500":
          description: "Ошибка запроса"
      security:
      - sso_auth: []
  /sandbox/currencies/balance:
    post:
      tags:
      - "sandbox"
      summary: "Выставление баланса по валютным позициям"
      parameters:
      - name: "brokerAccountId"
        in: "query"
        description: "Номер счета (по умолчанию - Тинькофф)"
        required: false
        x-exportParamName: "BrokerAccountId"
      responses:
        "200":
          description: "Успешный ответ"
        "500":
          description: "Ошибка запроса"
      security:
      - sso_auth: []
  /sandbox/positions/balance:
    post:
      tags:
      - "sandbox"
      summary: "Выставление баланса по инструментным позициям"
      parameters:
      - name: "brokerAccountId"
        in: "query"
        description: "Номер счета (по умолчанию - Тинькофф)"
        required: false
        x-exportParamName: "BrokerAccountId"
      responses:
        "200":
          description: "Успешный ответ"
        "500":
          description: "Ошибка запроса"
      security:
      - sso_auth: []
  /sandbox/remove:
    post:
      tags:
      - "sandbox"
      summary: "Удаление счета"
      description: "Удаление счета клиента"
      parameters:
      - name: "brokerAccountId"
        in: "query"
        description: "Номер счета (по умолчанию - Тинькофф)"
        required: false
        x-exportParamName: "BrokerAccountId"
      responses:
        "200":
          description: "Успешный ответ"
        "500":
          description: "Ошибка запроса"
      security:
      - sso_auth: []
  /sandbox/clear:
    post:
      tags:
      - "sandbox"
      summary: "Удаление всех позиций"
      description: "Удаление всех позиций клиента"
      parameters:
      - name: "brokerAccountId"
        in: "query"
        description: "Номер счета (по умолчанию - Тинькофф)"
        required: false
        x-exportParamName: "BrokerAccountId"
      responses:
        "200":
          description: "Успешный ответ"
        "500":
          description: "Ошибка запроса"
      security:
      - sso_auth: []
  /orders:
    get:
      tags:
      - "orders"
      summary: "Получение списка активных заявок"
      parameters:
      - name: "brokerAccountId"
        in: "query"
        description: "Номер счета (по умолчанию - Тинькофф)"
        required: false
        x-exportParamName: "BrokerAccountId"
      responses:
        "200":
          description: "Список заявок"
        "500":
          description: "Инструмент не найден"
      security:
      - sso_auth: []
  /orders/limit-order:
    post:
      tags:
      - "orders"
      summary: "Создание лимитной заявки"
      parameters:
      - name: "figi"
        in: "query"
        description: "FIGI инструмента"
        required: true
        x-exportParamName: "Figi"
      - name: "brokerAccountId"
        in: "query"
        description: "Номер счета (по умолчанию - Тинькофф)"
        required: false
        x-exportParamName: "BrokerAccountId"
      responses:
        "200":
          description: "Созданная заявка"
        "500":
          description: "Ошибка запроса"
      security:
      - sso_auth: []
  /orders/cancel:
    post:
      tags:
      - "orders"
      summary: "Отмена заявки"
      parameters:
      - name: "orderId"
        in: "query"
        description: "ID заявки"
        required: true
        x-exportParamName: "OrderId"
      - name: "brokerAccountId"
        in: "query"
        description: "Номер счета (по умолчанию - Тинькофф)"
        required: false
        x-exportParamName: "BrokerAccountId"
      responses:
        "200":
          description: "Успешный ответ"
        "500":
          description: "Ошибка запроса"
      security:
      - sso_auth: []
  /operations:
    get:
      tags:
      - "operations"
      summary: "Получение списка операций"
      parameters:
      - name: "from"
        in: "query"
        description: "Начало временного промежутка"
        required: true
        x-exportParamName: "From"
      - name: "to"
        in: "query"
        description: "Конец временного промежутка"
        required: true
        x-exportParamName: "To"
      - name: "figi"
        in: "query"
        description: "Figi инструмента для фильтрации"
        required: false
        x-exportParamName: "Figi"
      - name: "brokerAccountId"
        in: "query"
        description: "Номер счета (по умолчанию - Тинькофф)"
        required: false
        x-exportParamName: "BrokerAccountId"
      responses:
        "200":
          description: "Список операций"
        "500":
          description: "Брокерский счет не найден"
      security:
      - sso_auth: []
  /portfolio:
    get:
      tags:
      - "portfolio"
      summary: "Получение портфеля клиента"
      parameters:
      - name: "brokerAccountId"
        in: "query"
        description: "Номер счета (по умолчанию - Тинькофф)"
        required: false
        x-exportParamName: "BrokerAccountId"
      responses:
        "200":
          description: "Успешный ответ"
        "500":
          description: "Брокерский счет не найден"
      security:
      - sso_auth: []
  /portfolio/currencies:
    get:
      tags:
      - "portfolio"
      summary: "Получение валютных активов клиента"
      parameters:
      - name: "brokerAccountId"
        in: "query"
        description: "Номер счета (по умолчанию - Тинькофф)"
        required: false
        x-exportParamName: "BrokerAccountId"
      responses:
        "200":
          description: "Успешный ответ"
        "500":
          description: "Брокерский счет не найден"
      security:
      - sso_auth: []
  /user/accounts:
    get:
      tags:
      - "user"
      summary: "Получение брокерских счетов клиента"
      parameters: []
      responses:
        "200":
          description: "Успешный ответ"
        "500":
          description: "Брокерский счет не найден"
      security:
      - sso_auth: []
  /market/stocks:
    get:
      tags:
      - "market"
      summary: "Получение списка акций"
      parameters: []
      responses:
        "200":
          description: "Успешный ответ"
        "500":
          description: "Инструмент не найден"
      security:
      - sso_auth: []
  /market/bonds:
    get:
      tags:
      - "market"
      summary: "Получение списка облигаций"
      parameters: []
      responses:
        "200":
          description: "Успешный ответ"
        "500":
          description: "Инструмент не найден"
      security:
      - sso_auth: []
  /market/etfs:
    get:
      tags:
      - "market"
      summary: "Получение списка ETF"
      parameters: []
      responses:
        "200":
          description: "Успешный ответ"
        "500":
          description: "Инструмент не найден"
      security:
      - sso_auth: []
  /market/currencies:
    get:
      tags:
      - "market"
      summary: "Получение списка валютных пар"
      parameters: []
      responses:
        "200":
          description: "Успешный ответ"
        "500":
          description: "Инструмент не найден"
      security:
      - sso_auth: []
  /market/orderbook:
    get:
      tags:
      - "market"
      summary: "Получение исторических стакана по FIGI"
      parameters:
      - name: "figi"
        in: "query"
        description: "FIGI"
        required: true
        x-exportParamName: "Figi"
      - name: "depth"
        in: "query"
        description: "Глубина стакана [1..20]"
        required: true
        x-exportParamName: "Depth"
      responses:
        "200":
          description: "Успешный ответ"
        "500":
          description: "Инструмент не найден"
      security:
      - sso_auth: []
  /market/candles:
    get:
      tags:
      - "market"
      summary: "Получение исторических свечей по FIGI"
      parameters:
      - name: "figi"
        in: "query"
        description: "FIGI"
        required: true
        x-exportParamName: "Figi"
      - name: "from"
        in: "query"
        description: "Начало временного промежутка"
        required: true
        x-exportParamName: "From"
      - name: "to"
        in: "query"
        description: "Конец временного промежутка"
        required: true
        x-exportParamName: "To"
      - name: "interval"
        in: "query"
        description: "Интервал свечи"
        required: true
        x-exportParamName: "Interval"
      responses:
        "200":
          description: "Успешный ответ"
        "500":
          description: "Инструмент не найден"
      security:
      - sso_auth: []
  /market/search/by-figi:
    get:
      tags:
      - "market"
      summary: "Получение инструмента по FIGI"
      parameters:
      - name: "figi"
        in: "query"
        description: "FIGI"
        required: true
        x-exportParamName: "Figi"
      responses:
        "200":
          description: "Успешный ответ"
        "500":
          description: "Инструмент не найден"
      security:
      - sso_auth: []
  /market/search/by-ticker:
    get:
      tags:
      - "market"
      summary: "Получение инструмента по тикеру"
      parameters:
      - name: "ticker"
        in: "query"
        description: "Тикер инструмента"
        required: true
        x-exportParamName: "Ticker"
      responses:
        "200":
          description: "Успешный ответ"
        "500":
          description: "Инструмент не найден"
      security:
      - sso_auth: []
definitions: {}
externalDocs:
  description: "Документация OpenApi"
  url: "https://api-invest.tinkoff.ru/openapi/docs/"
